name = "series"
defaultTargets = ["Series"]
testDriver = "SeriesTest"

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "interval"
scope = "girving"
rev = "broken"

[[lean_lib]]
name = "Series"

[[lean_lib]]
name = "SeriesTest"
globs = ["test.+"]
leanOptions = {linter.unusedVariables = false}
